# Generated by Django 5.1.7 on 2025-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcessFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('food_type', models.CharField(choices=[('Cooked', 'Cooked'), ('Packaged', 'Packaged'), ('Raw', 'Raw')], max_length=20)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('servings', models.PositiveIntegerField()),
                ('best_before', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('pickup_datetime', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
