# Generated by Django 5.1.7 on 2025-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excess', '0002_excessfood_donor_alter_excessfood_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excessfood',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='cuisine_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='food_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='excessfood',
            name='servings',
            field=models.PositiveIntegerField(),
        ),
    ]
